
# ~/.cargo/config.toml

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[build]
rustc-wrapper = "/home/rustdevuser/.cargo/bin/sccache"
